### ISSUE TITLE
Error when compiling with VS

### ISSUE THREAD

**Issue by 1vanK** [LucKeyProductions/Quatter#2]
```
float LucKey::Cycle(float x, float min, float max)
{
    ...
    int range{max - min};
    ...
}
```

Error	C2397	conversion from 'float' to 'int' requires a narrowing conversion	D:\MyGames\Quarto\GameSrc\luckey.cpp	138	

Fixed version:

```
int range = max - min;
```

**Comment by Modanung** [comment]
Oops, forgot to commit. Had corrected that locally.
